-- INVOICE에 없고, SCSDAY에 정상반품 차이분 조회
SELECT *
FROM(
SELECT    A.SEASON, SC.SORT, A.PARTCODE, B.PARTCODENAME,B.SELLPRICE, NVL(C.STOCK_POCOST,0), B.IMAGENAME, A.COLOR, A.SIZ
        , SUM( CASE WHEN WDATE < '2024-01-30' THEN NVL(A.ACCEPT_QTY + A.TAKEOUT_CQTY - A.ACCEPT_CQTY - A.TAKEOUT_QTY,0) ELSE 0 END)  AS      YESTERDAYQTY
        , SUM( CASE WHEN WDATE >= '2024-01-30' THEN NVL(A.ACCEPT_QTY - A.ACCEPT_CQTY,0) ELSE 0 END)       AS      ACCEPTQTY
        , SUM( CASE WHEN WDATE >= '2024-01-30' THEN NVL(A.TAKEOUT_QTY,0) - NVL(A.BADTAKEOUT_QTY,0) ELSE 0 END)    AS      TAKEOUTQTY
        , SUM( CASE WHEN WDATE >= '2024-01-30' THEN NVL(A.TAKEOUT_CQTY,0) - NVL(A.BADTAKEOUT_CQTY,0) ELSE 0 END)  AS      TRETURNQTY
        , SUM( NVL(A.ACCEPT_QTY + A.TAKEOUT_CQTY - A.ACCEPT_CQTY - A.TAKEOUT_QTY,0)) AS   NOWQTY
        , SUM( NVL(A.ACCEPT_QTY + A.TAKEOUT_CQTY - A.ACCEPT_CQTY - A.TAKEOUT_QTY,0)) - SUM( NVL((A.BADTAKEOUT_CQTY - NVL(A.DISUSE_CQTY,0)) - (A.BADTAKEOUT_QTY - NVL(A.DISUSE_QTY,0)),0) ) - SUM( NVL(NVL(A.DISUSE_CQTY,0) - NVL(A.DISUSE_QTY,0),0) )     AS      NOMALQTY
        , SUM( NVL((A.BADTAKEOUT_CQTY - NVL(A.DISUSE_CQTY,0)) - (A.BADTAKEOUT_QTY - NVL(A.DISUSE_QTY,0)),0) ) AS  BADQTY
        , SUM( CASE WHEN WDATE >= '2024-01-30' THEN NVL(A.BADTAKEOUT_CQTY - NVL(A.DISUSE_CQTY,0),0) ELSE 0 END)
        , SUM( CASE WHEN WDATE >= '2024-01-30' THEN NVL(A.BADTAKEOUT_QTY - NVL(A.DISUSE_QTY,0),0) ELSE 0 END)
        , SUM( NVL(NVL(A.DISUSE_CQTY,0) - NVL(A.DISUSE_QTY,0),0) ) AS DISUSEQTY
        , SUM( CASE WHEN WDATE >= '2024-01-30' THEN NVL(A.DISUSE_CQTY,0) ELSE 0 END)
        , SUM( CASE WHEN WDATE >= '2024-01-30' THEN NVL(A.DISUSE_QTY,0) ELSE 0 END)
        , SUM( NVL(A.ACCEPT_QTY + A.TAKEOUT_CQTY - A.ACCEPT_CQTY - A.TAKEOUT_QTY,0) * B.SELLPRICE) AS      NOWQTYTAGAMT
        , SUM( NVL(A.ACCEPT_QTY + (A.TAKEOUT_CQTY - A.ADJUST_CQTY) - A.ACCEPT_CQTY - (A.TAKEOUT_QTY - A.ADJUST_QTY),0) * B.SELLPRICE) - SUM( NVL( (A.BADTAKEOUT_CQTY - NVL(A.DISUSE_CQTY,0)) - (A.BADTAKEOUT_QTY - NVL(A.DISUSE_QTY,0)),0) * B.SELLPRICE ) - SUM( NVL(NVL(A.DISUSE_CQTY,0) - NVL(A.DISUSE_QTY,0),0) * B.SELLPRICE ) AS    NOMALQTYTAGAMT
        , SUM( NVL((A.BADTAKEOUT_CQTY - NVL(A.DISUSE_CQTY,0)) - (A.BADTAKEOUT_QTY - NVL(A.DISUSE_QTY,0)),0) * B.SELLPRICE ) AS BADTAGAMT
        , SUM( NVL(NVL(A.DISUSE_CQTY,0) - NVL(A.DISUSE_QTY,0),0) * B.SELLPRICE ) AS DISUSETAGAMT
FROM      SCSDAY A, VIEW_PARTS_INFO B, PRODUCTRND C ,SEASON SC
WHERE     A.BRAND  = B.BRAND
AND A.SEASON = B.SEASON
AND A.PARTCODE  = B.PARTCODE
AND A.WDATE <= '2024-01-30'
AND A.BRAND = 'X'
AND A.SEASON IN ('23F')
AND A.BRAND = C.BRAND (+)
AND A.SEASON = C.SEASON (+)
AND A.PARTCODE = C.PARTCODE (+)
AND C.YYYYMM (+) = '202-01'
AND A.SEASON = SC.SEASON
AND NOT ( B.ITEM = 'SAM' AND B.SUBSEASON = '9')
AND (A.PARTCODE, A.COLOR, A.SIZ) NOT IN (SELECT
                                                  C.PARTCODE, C.COLOR, C.SIZ
                                         FROM     INVOICES B
                                                , CUSTOMS A
                                                , INVITEMS C
                                        WHERE     A.BRAND = B.BRAND
                                          AND     A.SHOPCODE = B.SHOPCODE
                                          AND     B.BRAND = C.BRAND
                                          AND     B.SEASON = C.SEASON
                                          AND     B.SORDERNUM = C.SORDERNUM
                                          AND     B.BRAND = 'X'
                                          AND     B.SEASON = '23F'
                                          AND     B.DUEDATE >= '2024-01-30'
                                          AND     B.DUEDATE <= '2024-01-30'
                                          AND     B.STATUS = 'C'
                                          AND     B.SOTYPE > '500'
                                        GROUP BY  A.SHOPCODE, A.SHORTNAME, B.SEASON, B.SORDERNUM, B.INVOICENUM, B.DUEDATE, B.PRICEDATE, B.SPPERSON, B.SALESPERSON, B.SOTYPE, B.STATUS, A.TYPE_MANAGE, C.COMMISSION, B.MAILTO, TO_CHAR(B.UPDATE_DATE,'YYYY-MM-DD'), C.PARTCODE, C.COLOR, C.SIZ )
GROUP BY A.SEASON ,SC.SORT, A.SEASON, A.PARTCODE,B.PARTCODENAME,B.SELLPRICE, B.IMAGENAME, NVL(C.STOCK_POCOST,0), A.COLOR, A.SIZ, ''
)
WHERE TRETURNQTY > 0
;