/**
  수출 인보이스 확인
 */
-- 1041
SELECT A.HIST_DE
     , A.HIST_SNO
     , A.INS_DIV_CD
     , A.IV_NO
     , REPLACE( A.ONBRD_DE, '-', '' ) AS ONBRD_DE
     , REPLACE( A.STMT_DE, '-', '' )  AS STMT_DE
     , A.DSH_YN
     , B.BRAND_CD
     , B.SSN_CD
     , B.ORD_NO
     , B.STD_SHOP_CD                  AS SHOP_CD
     , REPLACE( B.GI_DE, '-', '' )    AS GI_DE
     , B.GI_TYP_CD
     , A.IV_TYP_CD
     , A.INCT_TYP_CD
  FROM BIM_EXP_ONBRD_HIST A
           INNER JOIN BIM_TRD_STTMT B
                      ON B.IV_NO = A.IV_NO
 WHERE 1 = 1
   AND A.SAP_IF_STCK_YN = 'N'
 ORDER BY A.HIST_DE
        , A.HIST_SNO;

-- 수출선적이력 (GOMS로 I/F 받는 테이블)
SELECT *
  FROM SERP.BIM_EXP_ONBRD_HIST
 WHERE IV_NO = 'EXPIV240409005SG';

-- 거래명세 테이블
SELECT *
  FROM SERP.BIM_TRD_STTMT
 WHERE IV_NO = 'EXPIV240409005SG';

-- SAP I/F 테이블 (1041)
SELECT *
  FROM SERP_IF.IF_SAP_EXP_TRD_STTMT_SND
 WHERE 1 = 1
   AND IV_NO = 'EXPIV240409005SG';


/**
  PRC_EXP_ONBRD_SAP_SND (수출 인터페이스 테이블 적재 프로시저)
 */

/*
SELECT DTL_CD_ATTR_VAL -- V_DTL_CD_ATTR_VAL -- AB
  FROM ESADTAT
 WHERE SYS_ID = 'FNF'
   AND GRP_CD = 'X007'
   AND DTL_CD = 'FOB'
   AND ATTR_CD = 'POSTING_VAT';
*/

-- RESULT) SHOP_CD : SG001
SELECT A.HIST_DE
     , A.HIST_SNO
     , A.INS_DIV_CD
     , A.IV_NO
     , REPLACE( A.ONBRD_DE, '-', '' ) AS ONBRD_DE
     , REPLACE( A.STMT_DE, '-', '' )  AS STMT_DE
     , A.DSH_YN
     , B.BRAND_CD
     , B.SSN_CD
     , B.ORD_NO
     , B.STD_SHOP_CD                  AS SHOP_CD
     , REPLACE( B.GI_DE, '-', '' )    AS GI_DE
     , B.GI_TYP_CD
     , A.IV_TYP_CD
     , A.INCT_TYP_CD
  FROM BIM_EXP_ONBRD_HIST A
           INNER JOIN BIM_TRD_STTMT B
                      ON B.IV_NO = A.IV_NO
 WHERE 1 = 1
   AND A.SAP_IF_STCK_YN = 'N'
 ORDER BY A.HIST_DE
        , A.HIST_SNO;

-- RESULT) V_SAP_MOV_TYP_CD : 1010
SELECT B.SAP_MOV_TYP_CD -- V_SAP_MOV_TYP_CD
  FROM BIM_SHOP A
           INNER JOIN BIM_SHOP_OPER B
                      ON B.BRAND_CD = A.BRAND_CD
                          AND B.SHOP_CD = A.SHOP_CD
 WHERE A.BRAND_CD = 'M'
   AND A.SHOP_CD = 'SG001';


-- RESULT) V_SAP_SALE_NOR : Z13 , V_SAP_SALE_RET : Z14
SELECT MAX( DECODE( E.ATTR_CD, 'VALUE_03', E.DTL_CD_ATTR_VAL ) ) -- V_SAP_SALE_NOR
     , MAX( DECODE( E.ATTR_CD, 'VALUE_04', E.DTL_CD_ATTR_VAL ) ) -- V_SAP_SALE_RET
  FROM ESACDGP A
     , ESACDDT B
     , ESACDDL C
     , ESACDAT D
     , ESADTAT E
 WHERE A.SYS_ID = 'FNF'
   AND A.GRP_CD = 'SAP_MOV_TYP_CD'
   AND A.SYS_ID = B.SYS_ID
   AND A.GRP_CD = B.GRP_CD
   AND B.SYS_ID = C.SYS_ID
   AND B.GRP_CD = C.GRP_CD
   AND B.DTL_CD = C.DTL_CD
   AND C.SYS_ID = D.SYS_ID
   AND C.GRP_CD = D.GRP_CD
   AND C.DTL_CD = E.DTL_CD
   AND D.SYS_ID = E.SYS_ID
   AND D.GRP_CD = E.GRP_CD
   AND D.ATTR_CD = E.ATTR_CD
   AND NVL( B.USE_YN, 'Y' ) = 'Y'
   AND C.LANG_CD = 'ko_KR'
   AND C.DTL_CD = '1010'
   AND A.STS != 'D'
   AND B.STS != 'D'
   AND C.STS != 'D'
   AND D.STS != 'D'
;