/*
거래명세 조회
*/

-- ORD_NO : 주문번호
-- IV_NO : 송장번호
-- GI_TYP_CD : sotype(출고유형코드)
-- GI_RAT : 출고율
-- SALE_TYP_CD : saletrtype(판매유형코드_
SELECT B.*
  FROM BIM_TRD_STTMT A
     , BIM_TRD_STTMT_DTL B
 WHERE 1 = 1
   AND A.BRAND_CD = B.BRAND_CD
   AND A.ORD_NO = B.ORD_NO
   AND A.SSN_CD = B.SSN_CD
   AND A.BRAND_CD = 'M'
   AND A.ORD_NO = 'M19F00702205'
   AND A.GI_STS_CD = 'C';


/**
  거래 명세 (인보이스) 금액 확인
 */
SELECT SUM( CASE WHEN A.GI_TYP_CD > 500 THEN -1 ELSE 1 END * B.GI_QTY )    AS 출고수량
     , SUM( CASE WHEN A.GI_TYP_CD > 500 THEN -1 ELSE 1 END * B.GI_AMT )    AS 출고금액
     , SUM( CASE WHEN A.GI_TYP_CD > 500 THEN -1 ELSE 1 END * B.VAT )       AS VAT
     , SUM( CASE WHEN A.GI_TYP_CD > 500 THEN -1 ELSE 1 END * B.FC_GI_AMT ) AS 외환출고금액
  FROM BIM_TRD_STTMT A
     , BIM_TRD_STTMT_DTL B
 WHERE 1 = 1
   AND A.BRAND_CD = B.BRAND_CD
   AND A.ORD_NO = B.ORD_NO
   AND A.SSN_CD = B.SSN_CD
   AND A.BRAND_CD = 'X'
   AND A.STD_SHOP_CD = '50001'
   AND A.GI_DE BETWEEN '2024-04-16' AND '2024-04-31'
--    AND A.ORD_NO = 'ST23F10003000001'
   AND A.GI_STS_CD = 'C';


/**
  SERP 기준 (기준월 판매수량, 실판매가)
 */
SELECT BRAND_CD
     , SHOP_CD
     , SAP_STMT_DE
     , SUM( CASE WHEN SALE_DIV_CD = 1 THEN 1 ELSE -1 END * SALE_QTY )     AS SALE_QTY
     , SUM( CASE WHEN SALE_DIV_CD = 1 THEN 1 ELSE -1 END * SALE_AMT )     AS SALE_AMT
     , SUM( CASE WHEN SALE_DIV_CD = 1 THEN 1 ELSE -1 END * ACT_SALE_AMT ) AS ACT_SALE_AMT
  FROM SERP.BIM_SALE_DTL
 WHERE BRAND_CD = 'X'
   AND SHOP_CD = '70001'
   AND SYS_CD IN ('POS', 'SMS', 'ERP', 'MIG', 'SERP')
--    AND SALE_DE >= '2018-01-01'
   AND SAP_STMT_DE BETWEEN '2024-04-01' AND '2024-04-30'
 GROUP BY BRAND_CD, SHOP_CD, SAP_STMT_DE
 ORDER BY SAP_STMT_DE;