-- SERP 기준 (기준월 판매수량, 실판매가)
SELECT BRAND_CD
     , SHOP_CD
     , SAP_STMT_DE
     , SUM( CASE WHEN SALE_DIV_CD = 1 THEN 1 ELSE -1 END * SALE_QTY )     AS SALE_QTY
     , SUM( CASE WHEN SALE_DIV_CD = 1 THEN 1 ELSE -1 END * SALE_AMT )     AS SALE_AMT
     , SUM( CASE WHEN SALE_DIV_CD = 1 THEN 1 ELSE -1 END * ACT_SALE_AMT ) AS ACT_SALE_AMT
  FROM SERP.BIM_SALE_DTL
 WHERE BRAND_CD = 'X'
   AND SHOP_CD = '70001'
   AND SYS_CD IN ('POS', 'SMS', 'ERP', 'MIG', 'SERP')
--    AND SALE_DE >= '2018-01-01'
   AND SAP_STMT_DE BETWEEN '2024-04-16' AND '2024-04-30'
 GROUP BY BRAND_CD, SHOP_CD, SAP_STMT_DE
 ORDER BY SAP_STMT_DE;
