/*
PDA (RFID) FUNCTION
*/
-- 1) 매장판매가 조회 (PDA) - 자동단가
SELECT SMS.FNC_IF_RFID_GET_SELL_PRICE_UID( 'M', '527', '23F', '3FTRB2034:43CRD' ) FROM DUAL;

-- 2) 상품이미지 조회 (PDA)
SELECT SMS.FNC_IF_RFID_GET_IMG_URL_UID('M', '23F','3FTRB2034','43CRD', '') FROM DUAL;

-- 3) 전산재고 정보
SELECT * FROM SERP.VIEW_IF_RFID_SA_STOCK_SHOP WHERE CD_DEPART = 'M' and CD_SHOP = '527';

--4) 로그인 정책

CALL SMS.PRC_IF_RFIDPDA_LOGIN('M524','test', :PSV_CODE, :PSV_MSG);
CALL SERP.PRC_IF_RFIDSTOCK_RECV('ADM', '1111', :VO_RTNCODE, :VO_RTNMSG);


