-- 전산재고 정보
SELECT * FROM SERP.VIEW_IF_RFID_SA_STOCK_SHOP WHERE CD_DEPART = 'M' and CD_SHOP = '527';

-- 생산 및 매장 마스터 정보
SELECT * FROM RFID_IF.VW_SHOP_RECV;

/*
SERP -> GERP 매장 마스터 정보
GERP_IF.SERP_PACKAGE_02.PRC_RCV_200;
SELECT * FROM GERP.SERP_SHOP_HD;
SELECT * FROM GERP.SERP_SHOP_DT;

유통망구분
FNF.CUSTOMS.TYPE_EDFM <-> GERP_IF.IF_R_SERP_SHOP_SND.DN_DIV_CD (유통망구분코드)
FNF.CUSTOMS.TYPE_SHOP <-> GERP_IF.IF_R_SERP_SHOP_SND.SHOP_TRD_TYP_CD (매장거래유형코드)
*/

-- EC온라인물류 3PL
/*(ASIS)*/SELECT * FROM FNF.VIEW_THIRD_PARTY_SHOP;
/*(TOBE)*/SELECT * FROM SMS.VIEW_THIRD_PARTY_SHOP;