-- 반품 지시목록 헤더
SELECT * FROM SMS.VIEW_IF_RETURNORDER_RECV WHERE 1=1 ORDER BY CD_RTN_REQ_NO DESC;

-- 반품 지시목록 디테일
SELECT * FROM SMS.VIEW_IF_RETURNORDER_SHOP_RECV WHERE 1=1 ORDER BY CD_RTN_REQ_NO DESC;

-- 반품이행정보
SELECT * FROM SMS_IF.IF_RFID_SHOP_RETURN_SEND WHERE 1=1 ORDER BY DT_IF_DATE DESC;

-- SMS 반품이행 수신 프로시저
CALL SMS.PRC_IF_RCV_RFID_SHOP_RETURN();

